targets:
  $default:
    builders:
      json_serializable:
        options:
          include_if_null: false
      sauri_api_generator|api_generator:
        enabled: true
        generate_for:
          - lib/data/api/**/*.dart

builders:
  api_generator:
    import: "package:sauri_api_generator/sauri_generator.dart"
    builder_factories: ["apiGeneratorBuilder"]
    build_extensions: {".dart": [".api.g.dart"]}
    auto_apply: dependents
    build_to: source